OhJungH/ycHacker

- .gitignore
- ycHackers/src/main/java/com/ych/pjt/controller/MainController.java
- ycHackers/src/main/java/com/ych/pjt/controller/UserController.java
- ycHackers/src/main/java/com/ych/pjt/dto/UserDataDto.java
- ycHackers/src/main/webapp/WEB-INF/spring/security-context.xml
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardHome.jsp
- ycHackers/src/main/webapp/WEB-INF/views/joinView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/loginView.jsp
- ycHackers/src/main/webapp/resources/style/joinView.css
home의 링크 준비, userDataDto, MainController, security-context, UserController에 링크 삽입 및 기본 파일 준비
+gitignore에서 /ycHackers/제
> feat:home, joinView, loginView View준비

- ycHackers/src/main/java/com/ych/pjt/HomeController.java
- ycHackers/src/main/webapp/WEB-INF/DB/SQL
> chore(homecontroller,SQL): 간단한수정

- ycHackers/src/main/java/com/ych/pjt/command/UserJoinCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/UserController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IUserDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/UserDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/userMapper.xml
- ycHackers/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- ycHackers/src/main/webapp/WEB-INF/views/joinView.jsp
- ycHackers/src/main/webapp/resources/style/joinView.css
> Yccho: join request, servlet-context fix

- ycHackers/src/main/webapp/WEB-INF/views/joinView.jsp
생년월일 검증이 잘 안되고 있음. javascript의 new Date에 대한 검증이 필요해보임.
> feat(join): data validation

- ycHackers/src/main/java/com/ych/pjt/controller/UserController.java
- ycHackers/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- ycHackers/src/main/webapp/WEB-INF/views/joinView.jsp
> chore(공란 제거, joinView): merge 순서에 따른 오류 수정

- ycHackers/src/main/java/com/ych/pjt/controller/MainController.java
- ycHackers/src/main/java/com/ych/pjt/controller/ResController.java
- ycHackers/src/main/webapp/WEB-INF/views/myResInfo.jsp
- ycHackers/src/main/webapp/resources/html/MyResInfo.html
MainController 
ResController 수정
> type : Chore

- ycHackers/src/main/java/com/ych/pjt/command/UserMainDataCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/UserController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IUserDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/UserDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/userMapper.xml
- ycHackers/src/main/java/com/ych/pjt/security/CustomUserDetailsService.java
- ycHackers/src/main/webapp/WEB-INF/DB/SQL
- ycHackers/src/main/webapp/WEB-INF/spring/security-context.xml
- ycHackers/src/main/webapp/WEB-INF/views/loginView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/logoutView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/html/main.html
- ycHackers/src/main/webapp/resources/style/top.css
userData database에 저장된 계정을 기준으로 로그인 처리.
> feat(log in/out): 로그인, 로그아웃 처리

- ycHackers/src/main/java/com/ych/pjt/controller/UserController.java
- ycHackers/src/main/java/com/ych/pjt/naver/NaverLoginApi.java
- ycHackers/src/main/java/com/ych/pjt/naver/NaverLoginBO.java
- ycHackers/src/main/webapp/WEB-INF/views/loginView.jsp
servlet-context에 social login을 위해 google과 naver bean 생성(mysql계정 이유로 push안함)
loginView에 막아놨던 EL문 재생성
네이버 로그인을 위한 파일 생성
UserController에 관련 의존성 주입 및 method 생성
각 SNS의 client_id, secret code는 git공유를 위해 제거
DB 처리는 아직안함.
> Feat(social login): google,naver,kakao 로그인 구현

- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardHomeCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/InfoController.java
- ycHackers/src/main/java/com/ych/pjt/controller/MainController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IInfoDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/InfoDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/infoMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/InfoBoardDto.java
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardHome.jsp
- ycHackers/src/main/webapp/resources/style/infoBoardHome.css
home에서 접근하는 공지게시판.
로그인하지 않으면 댓글 기능 불가
공지 종류에따라 style 변경되도록 준비
MainController에 있던 request mapping(infoBoardHome request 이동)
> Style: infoBoard from home style

- ycHackers/src/main/webapp/WEB-INF/spring/security-context.xml
> hotFix(security-context): 파일 오류 재도전

- ycHackers/src/main/webapp/WEB-INF/views/admin.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/html/admin.html
- ycHackers/src/main/webapp/resources/style/admin.css
- ycHackers/src/main/webapp/resources/style/footer.css
- ycHackers/src/main/webapp/resources/style/main.css
- ycHackers/src/main/webapp/resources/style/top.css
admin양식 조정, main의 nav에 home 버튼 삽입, footer와 mainRagion사이의 간격 조정 등
> feat: admin page 양식 조정

- ycHackers/src/main/java/com/ych/pjt/command/MyResInfoCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/ResController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/ResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/resMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/myResInfoView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resForm.jsp
내예약정보에 예약 정보 표시
예약하기에 top,footer css추가
> type : feat

- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardManageCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardPageListCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/controller/InfoController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IInfoDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/InfoDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/infoMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/adminPage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardManage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardPList.jsp
- ycHackers/src/main/webapp/WEB-INF/views/userGrade.jsp
- ycHackers/src/main/webapp/resources/html/adminManage.html
- ycHackers/src/main/webapp/resources/js/jquery.twbsPagination.js
- ycHackers/src/main/webapp/resources/style/admin.css
- ycHackers/src/main/webapp/resources/style/adminManage.css
admin page 양식 변경
공지 게시판 관리 페이지 접근 준비(+pagination)
userGrade 양식 변경
page가 길어지면 양식을 넘어갈수 있음(35개로 테스트했을때 넘어감)
> feat: 공지게시판, 관리자 페이지 양식

- ycHackers/src/main/java/com/ych/pjt/command/ResCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/ResController.java
- ycHackers/src/main/java/com/ych/pjt/dao/ResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/resMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/ResDto.java
- ycHackers/src/main/webapp/WEB-INF/DB/SQL
- ycHackers/src/main/webapp/WEB-INF/views/myResInfoView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resForm.jsp
cafePhone추가로 SQL문, dto,command,resmapper,resform 수정 내예약정보 보기에 cafePhone 데이터 추가
> feat:예약하기 폼에 cafePhone추가 하고 mysql에 연동

- ycHackers/src/main/webapp/WEB-INF/views/infoBoardWriteForm.jsp
- ycHackers/src/main/webapp/resources/html/infoBoardWriteForm.html
- ycHackers/src/main/webapp/resources/js/infoBoardWRadioStyle.js
- ycHackers/src/main/webapp/resources/js/infoBoardWValidation.js
- ycHackers/src/main/webapp/resources/style/infoBoardWriteForm.css
알림 게시판 디자인 작성.
javascript로 비동기 스타일 변경과 validation진행
> Style: 알림게시판 작성 form

- ycHackers/src/main/java/com/ych/pjt/command/MyResInfoPageListCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/ResController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/ResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/resMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/WEB-INF/views/myPageView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/myResInfoView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resCancelView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resForm.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resModifyView.jsp
내예약정보에 예약 변경,취소 아이콘 추가, pagination(진행중)
> feat : main에 id 클릭하면 myPage로 이동, 예약 변경,취소 페이지 생성,

- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
> chore: userList의 sql문 오타 수정

- ycHackers/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
> docs : servlet

- ycHackers/src/main/java/com/ych/pjt/command/StudyroomWriteCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/controller/CafeController.java
- ycHackers/src/main/java/com/ych/pjt/controller/UserController.java
- ycHackers/src/main/java/com/ych/pjt/dao/CafeDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/ICafeDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/cafeMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/CafeDto.java
- ycHackers/src/main/webapp/WEB-INF/views/studyroomwrite.jsp
StudyroomWriteCommand, CafeController, UserController, cafeDao, CafeMapper 수정
> feat : studyroomwrite 등록 처리중

- ycHackers/src/main/java/com/ych/pjt/dto/InfoEditorDto.java
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardManage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardWriteForm.jsp
- ycHackers/src/main/webapp/resources/style/infoBoardWriteForm.css
> feat:공지게시판 입력폼 조정

- ycHackers/src/main/webapp/WEB-INF/spring/security-context.xml
CK Editor의 이미지 처리를 위한 request 보안 과정을 면제하기 위해 security-context.xml 수정
> build:공지게시판의 CKEditor적용을 위한 연결처리

- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardWriteCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/InfoBoardDto.java
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardWriteForm.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
CK editor 적용 > validation 기능 > form submit > model > ajax > jsp
> Feat: 공지사항 입력기능

- ycHackers/src/main/java/com/ych/pjt/command/ResModifyCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/ResController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/ResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/resMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/myResInfoView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resModifyView.jsp
> feat : 내 예약 정보에서 예약변경 클릭하면 예약 데이터 나옴

- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardManageCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardPageListCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardWriteCommand.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/adminPage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardHome.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardManage.jsp
- ycHackers/src/main/webapp/resources/style/admin.css
- ycHackers/src/main/webapp/resources/style/adminManage.css
- ycHackers/src/main/webapp/resources/style/infoBoardHome.css
홈에서 호출하는 화면, admin page에서 list를 확인할페이지, pagination을 위한 attribute 삽입 등
> Chore: 공지게시판 관련 변경사항

- ycHackers/src/main/java/com/ych/pjt/command/InfoListMainCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/UserController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/IAdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/UserDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/DB/SQL
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/style/infoBoardHome.css
- ycHackers/src/main/webapp/resources/style/main.css
[Feat:main page개선, 공지게시판 List구현 페이지 편집](https://github.com/OhJungH/ycHacker/commit/b67949b23405f1721a29852e8df9b3c703673d8e)
[feat: 회원정보 호출시 authority 명칭 변경용 method추가](https://github.com/OhJungH/ycHacker/commit/96d95621aaa21dbc83f4b65bedb19eae34d66997)
> [Feat:main page개선, 공지게시판 List구현 페이지 편집]

- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardListCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/webapp/WEB-INF/views/adminPage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/html/infoBoardList.html
- ycHackers/src/main/webapp/resources/style/infoBoardList.css
- ycHackers/src/main/webapp/resources/style/main.css
html로 만든 prototype과 관련 model처리 준비
main에 공지사항과 도움말 nav탭 분리
> Style: main에서 공지게시판 접근을 위한 디자인

- ycHackers/src/main/java/com/ych/pjt/command/InfoBoardPagelistCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoManagePagelistCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/IAdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/infoBoard.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardPageList.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoManagePageList.jsp
- ycHackers/src/main/webapp/resources/style/admin.css
- ycHackers/src/main/webapp/resources/style/infoBoardList.css
- ycHackers/src/main/webapp/resources/style/main.css
list해온 것을 pagination하고 filter를적용
> Feat: main에서 공지사항 list 표시

- ycHackers/src/main/java/com/ych/pjt/command/CafeDetailCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/CafeController.java
- ycHackers/src/main/java/com/ych/pjt/dao/CafeDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/cafeMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/cafeDetail.jsp
- ycHackers/src/main/webapp/WEB-INF/views/cafeList.jsp
> feat : cafeseq

- ycHackers/src/main/webapp/WEB-INF/views/infoBoard.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardManage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardPageList.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoManagePageList.jsp
- ycHackers/src/main/webapp/WEB-INF/views/loginView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/html/adminManage.html
- ycHackers/src/main/webapp/resources/style/infoBoardList.css
- ycHackers/src/main/webapp/resources/style/loginView.css
- ycHackers/src/main/webapp/resources/style/main.css
- ycHackers/src/main/webapp/resources/style/top.css
pagination, js filter의 동시 적용을 위한 수정. main userInfoBox의 중복링크 정정(권한의 링크제거) main.css와 top.css 정리
다음 할일: home, main, infoBoard, adminManage, infoManage에서 접근할 details 처리
> chore: 공지게시판 List 관련 양식 수정

- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/html/infoDetailsHome.html
- ycHackers/src/main/webapp/resources/html/infoDetailsUser.html
- ycHackers/src/main/webapp/resources/html/main.html
- ycHackers/src/main/webapp/resources/style/infoBoardHome.css
> Style:infoDetails 준비

- ycHackers/src/main/java/com/ych/pjt/command/CafeDetailCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/CafeController.java
- ycHackers/src/main/java/com/ych/pjt/dao/CafeDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/ICafeDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/cafeMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/CafeDto.java
- ycHackers/src/main/webapp/WEB-INF/views/cafeDetail.jsp
- ycHackers/src/main/webapp/WEB-INF/views/cafeList.jsp
> feat : cafeList 수정

- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
group추가, 조회수를 처리할 infoBoarHit method추가
> Feat:공지사항 업로드시 누락되던 data처리, 조회수 처리

- ycHackers/src/main/java/com/ych/pjt/command/CafeDetailCommand.java
- ycHackers/src/main/webapp/WEB-INF/views/cafeDetail.jsp
- ycHackers/src/main/webapp/WEB-INF/views/cafeList.jsp
- ycHackers/src/main/webapp/resources/html/cafe.html
> feat : cafeDetail.jsp

- ycHackers/src/main/java/com/ych/pjt/command/InfoDetailsUserCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/IAdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/DB/SQL
- ycHackers/src/main/webapp/WEB-INF/views/infoBoard.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardPageList.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoDetailsUser.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/html/mainDefault.html
- ycHackers/src/main/webapp/resources/style/infoDetailsUser.css
- ycHackers/src/main/webapp/resources/style/main.css
- ycHackers/src/main/webapp/resources/style/top.css
[Feat: 유저용 공지사항 상세페이지](https://github.com/OhJungH/ycHacker/commit/d401c0eef2778d7716b1fc7c009b851899faf1da) 
@[cheerdearhere](https://github.com/OhJungH/ycHacker/commits?author=cheerdearhere)
cheerdearhere committed 1 minute ago
[DOCS:공지게시판 시범 data삽입](https://github.com/OhJungH/ycHacker/commit/f909d5a86655093b9831175ffe684ee09fa00ae6) 
@[cheerdearhere](https://github.com/OhJungH/ycHacker/commits?author=cheerdearhere)
cheerdearhere committed 7 hours ago
[Feat:공지사항 업로드시 누락되던 data처리, 조회수 처리](https://github.com/OhJungH/ycHacker/commit/775ced7649ba95b792beb376a8005854c6e1dd93) 
@[cheerdearhere](https://github.com/OhJungH/ycHacker/commits?author=cheerdearhere)
cheerdearhere committed 7 hours ago
> Yccho([Feat: 유저용 공지사항 상세페이지]/[DOCS:공지게시판 시범 data삽입]/[Feat:공지사항 업로드시 누락되던 data처리, 조회수 처리])

- ycHackers/src/main/java/com/ych/pjt/command/InfoDetailsModalCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoDetailsPreviewCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoModifyViewCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/IAdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/adminPage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardManage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardWriteForm.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoDetailsPreview.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoModifyView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/html/infoModifyView.html
- ycHackers/src/main/webapp/resources/js/infoBoardMRadioStyle.js
- ycHackers/src/main/webapp/resources/js/infoBoardMValidation.js
- ycHackers/src/main/webapp/resources/js/infoBoardWRadioStyle.js
- ycHackers/src/main/webapp/resources/style/admin.css
- ycHackers/src/main/webapp/resources/style/footer.css
- ycHackers/src/main/webapp/resources/style/infoDetailsPreview.css
- ycHackers/src/main/webapp/resources/style/infoModifyView.css
- ycHackers/src/main/webapp/resources/style/main.css
- ycHackers/src/main/webapp/resources/style/top.css
상세보기 처리 완료
modifyView와 modify는 진행중
> Feat: 공지게시판 detailsView처리.

- ycHackers/src/main/java/com/ych/pjt/command/ResModify1Command.java
- ycHackers/src/main/java/com/ych/pjt/controller/ResController.java
- ycHackers/src/main/java/com/ych/pjt/dao/IResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/ResDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/resMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/ResDto.java
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/WEB-INF/views/myPageView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/myResInfoView.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resForm.jsp
- ycHackers/src/main/webapp/WEB-INF/views/resModifyView.jsp
- ycHackers/src/main/webapp/resources/style/myPageView.css
> feat : 예약변경 기능, 페이지 이동 ajax문 추가

- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/IAdminDao.java
- ycHackers/src/main/webapp/WEB-INF/views/joinView.jsp
- ycHackers/src/main/webapp/resources/js/infoBoardWValidation.js
- ycHackers/src/main/webapp/resources/style/joinView.css
관리자 관련 Controller, Dao interface, Dao class 주석 및 정렬 회원가입 창에 도움말 추가
공지글 작성시 validation으로 사용하는 object를 const에서 let 또는 var로 변경해 생성중복으로 인한 오류 제거
> docs: admin관련 주석 및 정리, 회원가입 양식 변경

- ycHackers/src/main/java/com/ych/pjt/controller/CafeController.java
> feat : studyroomwrite enroll fix

- ycHackers/src/main/java/com/ych/pjt/command/CafeListCommand.java
- ycHackers/src/main/java/com/ych/pjt/dao/CafeDao.java
- ycHackers/src/main/webapp/WEB-INF/views/cafeList.jsp
> feat : 검색 기능 처리중

- ycHackers/src/main/java/com/ych/pjt/command/InfoReplyTermCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/IAdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/infoDetailsUser.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
몇가지 자료정리
댓글 기능을 위한 공지사항 list mapper 내용 수정
10분당 한건 작성을 위한 기능을 넣으려 했으나 방향 수정이 필요해보임.
> chore(admin):공지사항 댓글기능 준비

- ycHackers/src/main/java/com/ych/pjt/command/CafeListCommand.java
- ycHackers/src/main/java/com/ych/pjt/dao/CafeDao.java
> feat : 검색 기능 처리중..

- ycHackers/src/main/java/com/ych/pjt/command/InfoReplyTermCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/infoDetailsUser.jsp
Server-Sent Events를 사용해 10분내 등록한 댓글을 체크하려했음.
DB에서 data를 호출하는 것에는 성공했으나 EventSource의 연결이 끊어지지않아 실패 다음에는 ajax로 @ResponseBody로 처리해야할 듯.
> test: 공지게시판에 댓글기능 구현 테스트

- ycHackers/src/main/java/com/ych/pjt/command/InfoReplyTermCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/webapp/WEB-INF/views/infoDetailsUser.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoModifyView.jsp
공지사항 댓글을 입력하기 전 10분내에 다른 댓글을 단 것이 있는지 체크하고 혹시 있으면 남은 시간을 표시해주는 기능 구현 댓글을 입력하는 기능은 아직 미구현
> Feat:infoBoard reply term check

- ycHackers/src/main/java/com/ych/pjt/dao/CafeDao.java
> feat : 에러 수정

- ycHackers/src/main/java/com/ych/pjt/command/InfoDetailsReplyListCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoReplyDeleteCommand.java
- ycHackers/src/main/java/com/ych/pjt/command/InfoReplyInsertCommand.java
- ycHackers/src/main/java/com/ych/pjt/controller/AdminController.java
- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/IAdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/InfoBoardDto.java
- ycHackers/src/main/webapp/WEB-INF/views/infoDetailsUser.jsp
댓글 작성 기능, 댓글 삭제 기능,
댓글 관련 작동시 해당 게시물의 댓글 호출
공지 상세페이지 호출시 해당 게시물의 댓글 호출기능
> Feat: 공지게시판 댓글 기능

- ycHackers/src/main/java/com/ych/pjt/dao/AdminDao.java
- ycHackers/src/main/java/com/ych/pjt/dao/mapper/adminMapper.xml
- ycHackers/src/main/java/com/ych/pjt/dto/InfoBoardDto.java
- ycHackers/src/main/webapp/WEB-INF/views/infoBoard.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardManage.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoBoardPageList.jsp
- ycHackers/src/main/webapp/WEB-INF/views/infoDetailsUser.jsp
- ycHackers/src/main/webapp/WEB-INF/views/main.jsp
- ycHackers/src/main/webapp/resources/style/infoDetailsUser.css
댓글 style
댓글 갯수를 체크해 list에서 보여주려했으나 실패.
> Style: 댓글 관련 style조정
